// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RogStock_ASPNetCore.Models_RogStock;

#nullable disable

namespace RogStock_ASPNetCore.Migrations
{
    [DbContext(typeof(RogStockDbContext))]
    [Migration("20260107132614_Initialise")]
    partial class Initialise
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.FindFieldInfo", b =>
                {
                    b.Property<int>("FfiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FFI_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FfiId"));

                    b.Property<int?>("FfiDecimalPlaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("FFI_DecimalPlaces")
                        .HasComment("Decimal Places");

                    b.Property<string>("FfiFieldDataType")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("FFI_FieldDataType")
                        .HasComment("Filed Data Type");

                    b.Property<int?>("FfiFieldLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("FFI_FieldLength")
                        .HasComment("Field Length");

                    b.Property<string>("FfiFieldname")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FFI_Fieldname")
                        .HasComment("Field Name");

                    b.Property<string>("FfiLabelText")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FFI_LabelText")
                        .HasComment("Label Text");

                    b.Property<int>("FfiOrder")
                        .HasColumnType("int")
                        .HasColumnName("FFI_Order")
                        .HasComment("Order In List");

                    b.Property<string>("FfiSearchType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FFI_SearchType");

                    b.Property<string>("FfiTableName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FFI_TableName")
                        .HasComment("Table Name");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("FfiId");

                    b.ToTable("Find_FieldInfo", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.FindRelation", b =>
                {
                    b.Property<int>("FfrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FFR_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FfrId"));

                    b.Property<bool>("FfrDistinct")
                        .HasColumnType("bit")
                        .HasColumnName("FFR_Distinct")
                        .HasComment("Distinct Search?");

                    b.Property<string>("FfrGroupBy")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FFR_GroupBy")
                        .HasDefaultValueSql("((0))")
                        .HasComment("Group By");

                    b.Property<bool>("FfrIsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("FFR_IsDefault")
                        .HasComment("Is Default?");

                    b.Property<string>("FfrOrderBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FFR_OrderBy")
                        .HasComment("Order By");

                    b.Property<string>("FfrOtherTableFields")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("FFR_OtherTableFields")
                        .HasComment("Fields From Other Tables");

                    b.Property<string>("FfrQualifiedJoin")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("FFR_QualifiedJoin")
                        .HasComment("Qualified Join");

                    b.Property<string>("FfrSearchCondition")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FFR_SearchCondition")
                        .HasComment("Search Condition");

                    b.Property<string>("FfrSearchType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FFR_SearchType")
                        .HasComment("Search Type");

                    b.Property<string>("FfrTableName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FFR_TableName")
                        .HasComment("Table name");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("FfrId");

                    b.ToTable("Find_Relations", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.FindSearchFieldDelete", b =>
                {
                    b.Property<int>("FndId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FND_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FndId"));

                    b.Property<string>("FndFieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FND_FieldName")
                        .HasComment("Field Name");

                    b.Property<int>("FndOrder")
                        .HasColumnType("int")
                        .HasColumnName("FND_Order")
                        .HasComment("Search Order");

                    b.Property<string>("FndSearchType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FND_SearchType")
                        .HasComment("Search Type");

                    b.Property<string>("FndTableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FND_TableName")
                        .HasComment("Table Name");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("FndId")
                        .HasName("PK_Find_SearchField");

                    b.ToTable("Find_SearchField_Delete?", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.LocTrn", b =>
                {
                    b.Property<int>("LoctId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOCT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoctId"));

                    b.Property<DateTime>("LoctDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LOCT_DateTime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date/Time");

                    b.Property<string>("LoctItemId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LOCT_ItemID")
                        .HasComment("Item ID");

                    b.Property<string>("LoctLocation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LOCT_Location")
                        .HasComment("Location");

                    b.Property<string>("LoctOldLocation")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LOCT_OldLocation")
                        .HasComment("Previous Name");

                    b.Property<string>("LoctOperation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LOCT_Operation")
                        .HasComment("Operation");

                    b.Property<decimal>("LoctQty")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("LOCT_Qty")
                        .HasComment("Quantity");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("LoctId");

                    b.ToTable("Loc_TRN", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.Login", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOG_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("LogPassword")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("LOG_Password")
                        .HasComment("Password");

                    b.Property<string>("LogUser")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LOG_User")
                        .HasComment("User");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("LogId");

                    b.ToTable("Login", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.LoginCurrent", b =>
                {
                    b.Property<int>("LogcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOGC_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogcId"));

                    b.Property<DateTime>("LogcDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LOGC_DateTime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date/Time Logged In");

                    b.Property<string>("LogcPcip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("LOGC_PCIP")
                        .HasComment("IP Address of PC");

                    b.Property<string>("LogcUser")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LOGC_User")
                        .HasComment("User");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("LogcId");

                    b.ToTable("Login_Current", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.LotTrn", b =>
                {
                    b.Property<int>("LottId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOTT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LottId"));

                    b.Property<DateTime>("LottDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LOTT_DateTime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date/Time");

                    b.Property<string>("LottItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LOTT_ItemID")
                        .HasComment("Item ID");

                    b.Property<string>("LottLocation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LOTT_Location")
                        .HasComment("Location");

                    b.Property<int>("LottNbr")
                        .HasColumnType("int")
                        .HasColumnName("LOTT_Nbr");

                    b.Property<string>("LottOperation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LOTT_Operation")
                        .HasComment("Operation");

                    b.Property<decimal>("LottQty")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("LOTT_Qty")
                        .HasComment("Quantity");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("LottId");

                    b.ToTable("Lot_TRN", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.MenuArea", b =>
                {
                    b.Property<int>("SecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SEC_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SecId"));

                    b.Property<string>("SecArea")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SEC_Area")
                        .HasComment("Menu Area");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("SecId");

                    b.ToTable("Menu_Areas", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.MenuGroup", b =>
                {
                    b.Property<int>("GrpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GRP_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrpId"));

                    b.Property<string>("GrpGroup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("GRP_Group")
                        .HasComment("Group");

                    b.Property<string>("GrpMenuItem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("GRP_MenuItem")
                        .HasComment("Menu Item Group Hass Access To");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("GrpId");

                    b.ToTable("Menu_Groups", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.MenuMenuItem", b =>
                {
                    b.Property<int>("MnuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MNU_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MnuId"));

                    b.Property<string>("MnuDisplayWhere")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MNU_DisplayWhere")
                        .HasComment("Display Where");

                    b.Property<string>("MnuMenuItemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MNU_MenuItemName")
                        .HasComment("Menu Item Name");

                    b.Property<string>("MnuMenuItemObject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MNU_MenuItemObject")
                        .HasComment("Menu Item Object");

                    b.Property<string>("MnuType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MNU_Type");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("MnuId");

                    b.ToTable("Menu_MenuItems", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.MenuUsersGroup", b =>
                {
                    b.Property<int>("UsrgrpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USRGRP__ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsrgrpId"));

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.Property<string>("UsrgrpGroup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("USRGRP_Group")
                        .HasComment("Group");

                    b.Property<string>("UsrgrpUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("USRGRP_User")
                        .HasComment("User");

                    b.HasKey("UsrgrpId");

                    b.ToTable("Menu_UsersGroups", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.StockDescription", b =>
                {
                    b.Property<int>("StkdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("STKD_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StkdId"));

                    b.Property<string>("StkdDesc")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("STKD_Desc")
                        .HasComment("Description");

                    b.Property<string>("StkdItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("STKD_ItemID")
                        .HasComment("Item ID");

                    b.Property<string>("StkdLongDesc")
                        .HasColumnType("text")
                        .HasColumnName("STKD_LongDesc")
                        .HasComment("Long Description");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("StkdId");

                    b.ToTable("Stock_Description", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.StockItem", b =>
                {
                    b.Property<int>("StkiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("STKI_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StkiId"));

                    b.Property<string>("StkiItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("STKI_ItemID")
                        .HasComment("Item ID");

                    b.Property<bool>("StkiLocLot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("STKI_LocLot")
                        .HasComment("Loc/Lot Tracking?");

                    b.Property<decimal>("StkiPrice")
                        .HasColumnType("money")
                        .HasColumnName("STKI_Price")
                        .HasComment("Price");

                    b.Property<string>("StkiProductFamily")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STKI_ProductFamily")
                        .HasComment("Product Family");

                    b.Property<string>("StkiUom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STKI_UOM")
                        .HasComment("Unit of Measure");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("StkiId");

                    b.ToTable("Stock_Items", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.StockLoc", b =>
                {
                    b.Property<int>("LocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOC_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocId"));

                    b.Property<string>("LocDescription")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LOC_Description");

                    b.Property<string>("LocItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LOC_ItemID")
                        .HasComment("Item ID");

                    b.Property<string>("LocLocation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LOC_Location")
                        .HasComment("Location");

                    b.Property<bool>("LocNonNet")
                        .HasColumnType("bit")
                        .HasColumnName("LOC_NonNet")
                        .HasComment("Non Net?");

                    b.Property<decimal>("LocQty")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("LOC_Qty")
                        .HasComment("Quantity");

                    b.Property<DateTime>("LocUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LOC_Updated")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date Updated");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("LocId");

                    b.ToTable("Stock_Loc", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.StockLot", b =>
                {
                    b.Property<int>("LotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOT_ID")
                        .HasComment("Lot Number");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LotId"));

                    b.Property<string>("LotItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LOT_ItemID")
                        .HasComment("Item ID");

                    b.Property<string>("LotLocation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LOT_Location")
                        .HasComment("Location");

                    b.Property<int?>("LotNbr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("LOT_Nbr");

                    b.Property<bool>("LotNonNet")
                        .HasColumnType("bit")
                        .HasColumnName("LOT_NonNet")
                        .HasComment("Non Net?");

                    b.Property<decimal>("LotQty")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("LOT_Qty")
                        .HasComment("Quantity");

                    b.Property<DateTime>("LotUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LOT_Updated")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date Updated");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("LotId");

                    b.ToTable("Stock_Lot", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.StockMedium", b =>
                {
                    b.Property<int>("StkmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("STKM_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StkmId"));

                    b.Property<string>("StkmItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("STKM_ItemID")
                        .HasComment("Item ID");

                    b.Property<string>("StkmPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("STKM_Path")
                        .HasComment("Path To File");

                    b.Property<string>("StkmType")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("STKM_Type")
                        .HasComment("Type");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("StkmId");

                    b.ToTable("Stock_Media", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.StockProductFamily", b =>
                {
                    b.Property<int>("StkpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("STKP_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StkpId"));

                    b.Property<string>("StkpDesc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("STKP_Desc")
                        .HasComment("Description");

                    b.Property<string>("StkpProductFamily")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("STKP_ProductFamily")
                        .HasComment("Product Family");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("StkpId");

                    b.ToTable("Stock_ProductFamily", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.StockUom", b =>
                {
                    b.Property<int>("StkuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("STKU_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StkuId"));

                    b.Property<string>("StkuDesc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STKU_Desc")
                        .HasComment("Description");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("StkuId");

                    b.ToTable("Stock_UOM", (string)null);
                });

            modelBuilder.Entity("RogStock_ASPNetCore.Models_RogStock.StockVendor", b =>
                {
                    b.Property<int>("StkvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("STKV_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StkvId"));

                    b.Property<string>("StkvItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("STKV_ItemID")
                        .HasComment("Item ID");

                    b.Property<bool>("StkvPreferred")
                        .HasColumnType("bit")
                        .HasColumnName("STKV_Preferred")
                        .HasComment("Preferred Vendor?");

                    b.Property<decimal>("StkvPrice")
                        .HasColumnType("money")
                        .HasColumnName("STKV_Price")
                        .HasComment("Price");

                    b.Property<int>("StkvVendorId")
                        .HasColumnType("int")
                        .HasColumnName("STKV_VendorID")
                        .HasComment("Vendor ID");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("timestamp");

                    b.HasKey("StkvId");

                    b.ToTable("Stock_Vendors", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
